apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: customer-report-collector
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-report-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: customer-report-collector-deployment
  labels:
    app: customer-report-collector
spec:
  selector:
    matchLabels:
      app: customer-report-collector
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-report-collector
    spec:
      containers:
        - name: customer-report-collector
          image: maxmorev/customer-report-collector:latest
          ports:
            - containerPort: 8080
              name: spring
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m" # 1/4 core
            limits:
              memory: "512Mi"
              cpu: "500m" # 1/2 core
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
