spring:
  application:
    name: customer-report-collector
  profiles:
    active: develop
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework: INFO

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#reactive-feign client
reactive:
  feign:
    logger:
      enabled: true
    client:
      config:
        customer-report-calculation:
          connectTimeout: 20000
          readTimeout: 20000


external:
  customer-report-calculation:
    url: http://customer-report-calculation:8080
    reports: /v1/reports/by/customer-id/{customerId}