server.port: 8080
#Open-feign client
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 20000
        loggerLevel: full

external:
  customer-report-calculation:
    url: http://customer-report-calculation:8080
    reports: /v1/reports/by/customer-id/{customerId}
